/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.designer.views;

import com.designers.dao.Dao;
import com.designers.domain.Profile;
import com.designers.domain.User;
import com.designers.utils.WrapLayout;
import com.formdev.flatlaf.ui.FlatButtonBorder;
import java.awt.FlowLayout;

/**
 *
 * @author carlo
 */
public class HomeWindow extends javax.swing.JFrame {

    
    private User loggedUser;
    private Profile profile;
    private Dao dao;
    
    /**
     * Creates new form HomeWindow
     */
    public HomeWindow() {
        initComponents();
        this.dao = new Dao();
        this.setLocationRelativeTo(null);
        WrapLayout wrapLayout = new WrapLayout();
        wrapLayout.setHgap(50);
        wrapLayout.setVgap(20);
        
        // Set the layouts for the scroll tabs
        this.containerCards.setLayout(wrapLayout);
        this.containeDesigners.setLayout(wrapLayout);
        
        
        this.panelCareers.setLayout(new FlowLayout());
        
        
        initData();
    }
    
    public HomeWindow(User loggedUser) {
        initComponents();
        this.dao = new Dao();
        
        
        this.setLocationRelativeTo(null);
        WrapLayout wrapLayout = new WrapLayout();
        wrapLayout.setHgap(50);
        wrapLayout.setVgap(20);
        
        // Set the layouts for the scroll tabs
        this.containerCards.setLayout(wrapLayout);
        this.containeDesigners.setLayout(wrapLayout);
        
        
        this.panelCareers.setLayout(new FlowLayout());
        
        this.loggedUser = loggedUser;
        
        // Init user data
        initUserData();
        
        initData();
    }
    
    private void initUserData() {
        // Get the profile from the logged user
        this.profile = this.dao.getProfileByUserId(this.loggedUser.getIdUser());
        
        if (profile != null) {
            this.buttonLogin.setText(this.profile.getName());
        } else 
            this.buttonLogin.setText(this.loggedUser.getEmail());
    }
    
    private void initData() {

        initCareers();
        initProjects();
        initDesigners();
        
    }
    
    private void initProjects() {
        this.containerCards.removeAll();
        
        for (int i = 0; i < 9; i++) {
            PanelCard card = new PanelCard();
            this.containerCards.add(card);
        }
        
        this.containerCards.revalidate();
        this.containerCards.repaint();
    }
    
    private void initCareers() {
        // Initalize available careers
        this.panelCareers.removeAll();
        for (int i = 0; i < 5; i++) {
            PanelCategory career = new PanelCategory();
            this.panelCareers.add(career);
        }
        
        this.panelCareers.revalidate();
        this.panelCareers.repaint();
    }
    
    private void initDesigners() {
        
        // Initialize designers
        this.containeDesigners.removeAll();
        
        for (int i = 0; i < 5; i++) {
            PanelDesigner designer = new PanelDesigner();
            this.containeDesigners.add(designer);
        }
        
        this.containeDesigners.revalidate();
        this.containeDesigners.repaint();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFram = new javax.swing.JPanel();
        panelNavbar = new javax.swing.JPanel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        buttonProjects = new javax.swing.JButton();
        buttonDesigners = new javax.swing.JButton();
        buttonLogin = new javax.swing.JButton();
        scrollCareers = new javax.swing.JScrollPane();
        panelCareers = new javax.swing.JPanel();
        tabbedPainBody = new javax.swing.JTabbedPane();
        scrollCards = new javax.swing.JScrollPane();
        containerCards = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        scrollDesigners = new javax.swing.JScrollPane();
        containeDesigners = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFram.setBackground(new java.awt.Color(247, 247, 247));
        panelFram.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNavbar.setBackground(new java.awt.Color(255, 255, 255));
        panelNavbar.setBorder(new org.edisoncor.gui.util.DropShadowBorder());

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/DesignersLogo.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        buttonProjects.setBackground(new java.awt.Color(255, 255, 255));
        buttonProjects.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonProjects.setForeground(new java.awt.Color(102, 102, 102));
        buttonProjects.setText("Proyectos");
        buttonProjects.setBorder(new FlatButtonBorder());
        buttonProjects.setBorderPainted(false);
        buttonProjects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonProjectsMouseClicked(evt);
            }
        });

        buttonDesigners.setBackground(new java.awt.Color(255, 255, 255));
        buttonDesigners.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonDesigners.setForeground(new java.awt.Color(102, 102, 102));
        buttonDesigners.setText("Diseñadores");
        buttonDesigners.setBorder(new FlatButtonBorder());
        buttonDesigners.setBorderPainted(false);
        buttonDesigners.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDesigners.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDesignersMouseClicked(evt);
            }
        });

        buttonLogin.setBackground(new java.awt.Color(255, 255, 255));
        buttonLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(0, 102, 153));
        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-profile.png"))); // NOI18N
        buttonLogin.setText("Iniciar sesion");
        buttonLogin.setBorder(new FlatButtonBorder());
        buttonLogin.setBorderPainted(false);
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNavbarLayout = new javax.swing.GroupLayout(panelNavbar);
        panelNavbar.setLayout(panelNavbarLayout);
        panelNavbarLayout.setHorizontalGroup(
            panelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavbarLayout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(buttonProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonDesigners, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLogin)
                .addGap(17, 17, 17))
        );
        panelNavbarLayout.setVerticalGroup(
            panelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavbarLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(panelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDesigners, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        panelFram.add(panelNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 899, -1));

        scrollCareers.setBorder(null);
        scrollCareers.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panelCareers.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout panelCareersLayout = new javax.swing.GroupLayout(panelCareers);
        panelCareers.setLayout(panelCareersLayout);
        panelCareersLayout.setHorizontalGroup(
            panelCareersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        panelCareersLayout.setVerticalGroup(
            panelCareersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        scrollCareers.setViewportView(panelCareers);

        panelFram.add(scrollCareers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, -1, -1));

        scrollCards.setBackground(new java.awt.Color(255, 255, 255));
        scrollCards.setBorder(null);
        scrollCards.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollCards.setMaximumSize(new java.awt.Dimension(897, 32767));
        scrollCards.setMinimumSize(new java.awt.Dimension(897, 5));
        scrollCards.setPreferredSize(new java.awt.Dimension(897, 100));

        containerCards.setBackground(new java.awt.Color(247, 247, 247));
        containerCards.setMaximumSize(new java.awt.Dimension(897, 32767));
        containerCards.setMinimumSize(new java.awt.Dimension(897, 110));

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerCardsLayout = new javax.swing.GroupLayout(containerCards);
        containerCards.setLayout(containerCardsLayout);
        containerCardsLayout.setHorizontalGroup(
            containerCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCardsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(594, Short.MAX_VALUE))
        );
        containerCardsLayout.setVerticalGroup(
            containerCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCardsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        scrollCards.setViewportView(containerCards);

        tabbedPainBody.addTab("ProjectsTab", scrollCards);

        scrollDesigners.setBackground(new java.awt.Color(255, 255, 255));
        scrollDesigners.setBorder(null);
        scrollDesigners.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDesigners.setToolTipText("");

        containeDesigners.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout containeDesignersLayout = new javax.swing.GroupLayout(containeDesigners);
        containeDesigners.setLayout(containeDesignersLayout);
        containeDesignersLayout.setHorizontalGroup(
            containeDesignersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
        );
        containeDesignersLayout.setVerticalGroup(
            containeDesignersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        scrollDesigners.setViewportView(containeDesigners);

        tabbedPainBody.addTab("DesignersTab", scrollDesigners);

        panelFram.add(tabbedPainBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, -1, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        new SignInWindow(this).setVisible(true);
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonProjectsMouseClicked
        // TODO add your handling code here:
        this.tabbedPainBody.setSelectedIndex(0);
    }//GEN-LAST:event_buttonProjectsMouseClicked

    private void buttonDesignersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDesignersMouseClicked
        // TODO add your handling code here:
        this.tabbedPainBody.setSelectedIndex(1);
    }//GEN-LAST:event_buttonDesignersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDesigners;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonProjects;
    private javax.swing.JPanel containeDesigners;
    private javax.swing.JPanel containerCards;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCareers;
    private javax.swing.JPanel panelFram;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JPanel panelNavbar;
    private javax.swing.JScrollPane scrollCards;
    private javax.swing.JScrollPane scrollCareers;
    private javax.swing.JScrollPane scrollDesigners;
    private javax.swing.JTabbedPane tabbedPainBody;
    // End of variables declaration//GEN-END:variables
}
