/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.designer.views;

/**
 *
 * @author carlo
 */
public class PanelCategory extends javax.swing.JPanel {

    private String category;
    private HomeWindow homeWindow;
    /**
     * Creates new form PanelCategory
     */
    public PanelCategory() {
        initComponents();
    }
    
    public PanelCategory(String categoryName, HomeWindow homeWindow) {
        initComponents();
        this.category = categoryName;
        
        this.btnCareer.setText(category);
        
        this.homeWindow = homeWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCareer = new javax.swing.JButton();

        setBackground(new java.awt.Color(247, 247, 247));

        btnCareer.setBackground(new java.awt.Color(0, 152, 255));
        btnCareer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCareer.setForeground(new java.awt.Color(255, 255, 255));
        btnCareer.setText("Nombre Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCareer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCareer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCareer;
    // End of variables declaration//GEN-END:variables
}
