/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.designers.views.designer;

import com.designer.views.HomeWindow;
import com.designers.dao.Dao;
import com.designers.dao.ProjectsDao;
import com.designers.domain.Image;
import com.designers.domain.Profile;
import com.designers.domain.Project;
import com.designers.domain.User;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import jnafilechooser.api.JnaFileChooser;

public class AddProjectWindow extends javax.swing.JFrame {

    private HomeWindow homeWindow;
    private User loggedUser;
    private Profile loggedProfile;
    
    private List<File> selectedImages;
    
    
    /**
     * Creates new form AddProjectWindow
     */
    public AddProjectWindow() {
        initComponents();
    }
    
    public AddProjectWindow(User loggedUser, HomeWindow homeWindow) {
        initComponents();
        this.setLocationRelativeTo(null);
    
        this.selectedImages = new ArrayList<>();
        
        this.loggedUser = loggedUser;
        this.homeWindow = homeWindow;
        
        Dao dao = new Dao();
        this.loggedProfile = dao.getProfileByUserId(this.loggedUser.getIdUser());
    }
    
    public void loadImages() {
        
        this.containerImages.removeAll();
        
        for (File selectedImage : selectedImages) {
            PanelImagePreview pImgPrev = new PanelImagePreview(selectedImage, this);
            this.containerImages.add(pImgPrev);
        }
        
        containerImages.revalidate();
        containerImages.repaint();
    }
    
    public void deleteImage(File image) {
        
        this.selectedImages.remove(image);
        loadImages();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fieldTittle = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        dateChooserStart = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateChooserFin = new com.toedter.calendar.JDateChooser();
        btnAddImage = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        containerImages = new javax.swing.JPanel();
        btnCreateProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar proyecto");

        fieldTittle.setBackground(new java.awt.Color(255, 255, 255));
        fieldTittle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldTittle.setForeground(new java.awt.Color(102, 102, 102));
        fieldTittle.setText("Proyecto de diseño");
        fieldTittle.setBorder(null);

        jLabel2.setText("Nombre del proyecto");

        fieldDescription.setBackground(new java.awt.Color(255, 255, 255));
        fieldDescription.setColumns(20);
        fieldDescription.setLineWrap(true);
        fieldDescription.setRows(5);
        fieldDescription.setText("Descripcion breve sobre lo que trata el proyecto realizado");
        jScrollPane1.setViewportView(fieldDescription);

        jLabel3.setText("Descripcion");

        dateChooserStart.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Fecha de inicio");

        jLabel5.setText("Fecha de fin (Opcional) ");

        dateChooserFin.setBackground(new java.awt.Color(255, 255, 255));

        btnAddImage.setBackground(new java.awt.Color(0, 153, 204));
        btnAddImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddImage.setForeground(new java.awt.Color(255, 255, 255));
        btnAddImage.setText("Agregar imagenes");
        btnAddImage.setBorderPainted(false);
        btnAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImageActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setBorder(null);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        containerImages.setBackground(new java.awt.Color(229, 229, 229));
        containerImages.setLayout(new javax.swing.BoxLayout(containerImages, javax.swing.BoxLayout.X_AXIS));
        jScrollPane2.setViewportView(containerImages);

        btnCreateProject.setBackground(new java.awt.Color(0, 153, 204));
        btnCreateProject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateProject.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateProject.setText("Crear proyecto");
        btnCreateProject.setBorderPainted(false);
        btnCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddImage)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2)
                                .addComponent(btnCreateProject)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldTittle, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateChooserStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateChooserFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserStart, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserFin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddImage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateProject, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImageActionPerformed
        // TODO add your handling code here:
        
        JnaFileChooser fc = new JnaFileChooser();

        fc.setTitle("Seleccionar imagenes");
        fc.setMultiSelectionEnabled(true);
        fc.addFilter("Todos los archivos", "*");
        fc.addFilter("Imagenes", "*.jpg", "*.png", "*.jpeg");        
        
        if (fc.showOpenDialog(this)) {
            File[] files = fc.getSelectedFiles();
            selectedImages.addAll(Arrays.asList(files));
            loadImages();
        }

    }//GEN-LAST:event_btnAddImageActionPerformed

    private void btnCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProjectActionPerformed
        // TODO add your handling code here:
        
        String tittle = this.fieldTittle.getText();
        String description = this.fieldDescription.getText();
        
        java.sql.Date startDate = new java.sql.Date(this.dateChooserStart.getDate().getTime());
        java.sql.Date endDate = new java.sql.Date(this.dateChooserFin.getDate().getTime());
        
        Project newProject = new Project(this.loggedProfile.getIdProfile(), tittle, description, startDate, endDate, endDate == null || endDate.toString().isEmpty());
        int newProjectId = ProjectsDao.insertProject(newProject);
        if (newProjectId != -1) {
            // Save images
            try {
                
                List<Image> images = new ArrayList<>();
                for (File selectedImage : this.selectedImages) {
                    images.add(new Image(Files.readAllBytes(selectedImage.toPath()), newProjectId));
                }
                if (ProjectsDao.saveImages(images)) {
                    JOptionPane.showMessageDialog(null, "Proyecto creado con exito");
                    this.homeWindow.initMyPortfolios();
                    this.dispose();
                } else 
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al guardar las imagenes");
                
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al agregar las imagenes");
                System.out.println("Error al guardar imagenes : " + e.getMessage());
            }
            
        } else
            JOptionPane.showMessageDialog(null, "Ocurrio un error al crear el proyecto");
    }//GEN-LAST:event_btnCreateProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProjectWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProjectWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProjectWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProjectWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProjectWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddImage;
    private javax.swing.JButton btnCreateProject;
    private javax.swing.JPanel containerImages;
    private com.toedter.calendar.JDateChooser dateChooserFin;
    private com.toedter.calendar.JDateChooser dateChooserStart;
    private javax.swing.JTextArea fieldDescription;
    private javax.swing.JTextField fieldTittle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
