/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.designers.views.designer;

import com.designer.views.*;
import com.designers.dao.CareersDao;
import com.designers.domain.Profile;
import com.designers.domain.Resume;
import java.awt.BorderLayout;
import java.io.File;
import java.nio.file.Files;
import java.sql.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jnafilechooser.api.JnaFileChooser;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import org.icepdf.ri.common.views.DocumentViewController;
import org.icepdf.ri.util.FontPropertiesManager;

public class CvWindowPreview extends javax.swing.JFrame {

    private Profile profile; 
    private SwingController swingController;
    private JPanel pdfViewerPanel;
    

    /**
     * Creates new form CvWindow
     */
    public CvWindowPreview() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.swingController = new SwingController();
        this.swingController.setIsEmbeddedComponent(true);
        
        FontPropertiesManager.getInstance().loadOrReadSystemFonts();
        
        try {
            SwingViewBuilder factory = new SwingViewBuilder(swingController);
            pdfViewerPanel = factory.buildViewerPanel();
            ComponentKeyBinding.install(swingController, pdfViewerPanel);
        
            this.containerPdfPreview.setLayout(new BorderLayout());
            this.containerPdfPreview.add(pdfViewerPanel, BorderLayout.CENTER);
        
            this.swingController.setPageFitMode(DocumentViewController.PAGE_FIT_WINDOW_HEIGHT, true);
            this.revalidate();
            this.repaint();
            this.pack();
        } catch (Exception e) {
            System.out.println("Error al abrir el doc: " + e.getMessage());
        }
        
        initData();
    }
    
    public CvWindowPreview(Profile profile) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.swingController = new SwingController();
        this.swingController.setIsEmbeddedComponent(true);
        this.profile = profile; 
        FontPropertiesManager.getInstance().loadOrReadSystemFonts();
        
        try {
            SwingViewBuilder factory = new SwingViewBuilder(swingController);
            pdfViewerPanel = factory.buildViewerPanel();
            ComponentKeyBinding.install(swingController, pdfViewerPanel);
        
            this.containerPdfPreview.setLayout(new BorderLayout());
            this.containerPdfPreview.add(pdfViewerPanel, BorderLayout.CENTER);
        
            this.swingController.setPageFitMode(DocumentViewController.PAGE_FIT_WINDOW_HEIGHT, true);
            this.revalidate();
            this.repaint();
            this.pack();
        } catch (Exception e) {
            System.out.println("Error al abrir el doc: " + e.getMessage());
        }
        
        initData();
    }
    
    private void initData() {
        
        this.labelNameCv.setText(this.profile.getName() + " " + this.profile.getLastname());
        
        List<Resume> resumes = CareersDao.getAllResumesByProfileId(this.profile.getIdProfile());
        
        if (!resumes.isEmpty()) {
            
            Resume resume = resumes.getFirst();
            this.swingController.openDocument(resume.getFileUrl());
            
            swingController.setPageFitMode(DocumentViewController.PAGE_FIT_WINDOW_HEIGHT, true);
            
            this.containerPdfPreview.revalidate();
            this.containerPdfPreview.repaint();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        labelNameCv = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        containerPdfPreview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelNameCv.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelNameCv.setForeground(new java.awt.Color(0, 153, 204));
        labelNameCv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNameCv.setText("Mi CV");

        containerPdfPreview.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout containerPdfPreviewLayout = new javax.swing.GroupLayout(containerPdfPreview);
        containerPdfPreview.setLayout(containerPdfPreviewLayout);
        containerPdfPreviewLayout.setHorizontalGroup(
            containerPdfPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        containerPdfPreviewLayout.setVerticalGroup(
            containerPdfPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(containerPdfPreview);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addComponent(labelNameCv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNameCv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CvWindowPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CvWindowPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CvWindowPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CvWindowPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CvWindowPreview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPdfPreview;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelNameCv;
    // End of variables declaration//GEN-END:variables
}
